### ISSUE TITLE
Evaluate gitbook alternatives

### ISSUE THREAD

**Issue by f0rki** [f0rki/mapping-high-level-constructs-to-llvm-ir#16]
I notice more and more that writing in markdown with gitbook is rather cumbersome. 
* (partial) source code includes require plugins with awkward and non-standard syntax
* markdown has no footnote support

gitbook does also support asciidoc, which has many interesting features and generally seems to be more suited for longer documents. Unfortunately asciidoc support seems rather bad in gitbook, e.g. source code include syntax is simply not supported (see [this issue](https://github.com/GitbookIO/gitbook/issues/1048) )

Maybe gitbook is not the best way to host this... Maybe using sphinx/readthedocs would be an alternative. afaik this would require switching to restructured text as markup.

**Comment by archfrog** [comment]
Markdown Extra does support [footnotes](https://michelf.ca/projects/php-markdown/extra/#footnotes), but I don't know if Gitbook uses plain markdown or allows for markdown extra.

I believe Sphinx is quite powerful.  The reason I didn't use it originally is that it is also somewhat brittle.  The parser was/is not very strict (regex-based, AFAIK) so sometimes you get something very different from what you think you're asking for.  LLVM itself uses Sphinx, though, so it must be doable.

Also, using an editor that strips trailing white-space off the end of lines, I strongly dislike markup formats that require you to end certain lines with one or two additional whitespaces (also bad for prints).

The above are some of the reasons I did my own format back when I decided to publish coding articles.  Most of the contemporary markup methods are either very cumbersome or not very strict syntax-wise.

**Comment by MattPD** [comment]
Perhaps https://readthedocs.org/?

Here's how it looks like for gcc-python-plugin:
http://gcc-python-plugin.readthedocs.io/en/latest/

Corresponding source (can be seen by expanding the arrow in the bottom-left corner, which also provides the access to the downloads in PDF/HTML/Epub): 
https://github.com/davidmalcolm/gcc-python-plugin/blob/master/docs/index.rst

**Comment by f0rki** [comment]
Yeah most of the issues/limitations with sphinx/rst are similar or worse with markdown.

I once had trouble because some markdown constructs are ambiguous when indenting nested lists with 2 spaces, but are not when indenting with 4 spaces. This is just horrible.

However I find markdown syntax better than rst. Asciidoc is IMHO the best of the three but tool support is horrible. 

Sphinx at least is software that has proven itself over time. For me it feels like gitbook/md has still a lot of issues typical for young projects... 

On October 17, 2017 10:37:28 PM GMT+02:00, Mikael Egevig <notifications@github.com> wrote:
>Markdown Extra does support
>[footnotes](https://michelf.ca/projects/php-markdown/extra/#footnotes),
>but I don't know if Gitbook uses plain markdown or allows for markdown
>extra.
>
>I believe Sphinx is quite powerful.  The reason I didn't use it
>originally is that it is also somewhat brittle.  The parser was/is not
>very strict (regex-based, AFAIK) so sometimes you get something very
>different from what you think you're asking for.  LLVM itself uses
>Sphinx, though, so it must be doable.
>
>Also, using an editor that strips trailing white-space off the end of
>lines, I strongly dislike markup formats that require you to end
>certain lines with one or two additional whitespaces (also bad for
>prints).
>
>The above are some of the reasons I did my own format back when I
>decided to publish coding articles.  Most of the contemporary markup
>methods are either very cumbersome or not very strict syntax-wise.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/f0rki/mapping-high-level-constructs-to-llvm-ir/issues/16#issuecomment-337362983

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by f0rki** [comment]
Yeah I also thought of readthedocs first. I will investigate and maybe try it.

Fortunately there is pandoc so converting shouldn't be a problem.

On October 17, 2017 11:45:02 PM GMT+02:00, Matt <notifications@github.com> wrote:
>Perhaps https://readthedocs.org/?
>
>Here's how it looks like for gcc-python-plugin:
>http://gcc-python-plugin.readthedocs.io/en/latest/
>
>Corresponding source (can be seen by expanding the arrow in the
>bottom-left corner, which also provides the access to the downloads in
>PDF/HTML/Epub): 
>https://github.com/davidmalcolm/gcc-python-plugin/blob/master/docs/index.rst
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/f0rki/mapping-high-level-constructs-to-llvm-ir/issues/16#issuecomment-337381951

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by f0rki** [comment]
I converted it to sphinx and have set up the page on readthedocs. Check it out and tell me what version you like more:

http://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/

**Comment by f0rki** [comment]
For reference the [rust book](https://doc.rust-lang.org/stable/book/first-edition/) uses [azerupi/mdBook](https://github.com/azerupi/mdBook), which also looks pretty good.

It seems readthedocs has support for building docs with this. But unfortunately this doesn't fix the issues with markdown... So it's not really that much of an advantage over using gitbook.

**Comment by archfrog** [comment]
Your link to [ReadTheDocs](http://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/) gives an permission denied/access error so I can't see it :-)

**Comment by f0rki** [comment]
http://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/sphinx/

**Comment by f0rki** [comment]
I switched to readthedocs now: https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io

**Comment by archfrog** [comment]
Looks fantastic to me!  :-)  

I'm not sure yet, but there is a slight chance that I will resume my work on the project that made me start with LLVM back in time.  This may take a while, though, but if it happens, I'll probably begin contributing to the project again.  The main reason I don't use LLVM is because of the mediocre Windows support.  I love Linux too, but about 95 percent of all systems are Windows system...  I still cannot understand that a large, extremely wealthy corporation such as Apple cannot invest a few dollars in adding Windows support to LLVM given the fact that they use LLVM internally.
