### ISSUE TITLE
Passing exception address by `longjmp`

### ISSUE THREAD

**Issue by vgxbj** [f0rki/mapping-high-level-constructs-to-llvm-ir#30]
In chapter [SjLj exception handling](https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/exception-handling/setjmp+longjmp-exception-handling.html), I noticed that we passed an address of pointer by `longjmp` which is not reasonable (IMO). Usually, when handling exception, we use `longjmp` to pass error/exception type, which is can be represent by a predefined integer. I didn't dig much about it, what's your opinion?

```llvm
%5 = ptrtoint %Exception* %3 to i32
call void @longjmp(%jmp_buf* %throw, i32 %5)
```

[1] [Setjmp.h on Wikipedia](https://en.wikipedia.org/wiki/Setjmp.h#Exception_handling)

Regards.

**Comment by archfrog** [comment]
I am to blame :)  I did the original sample for 32-bit architectures.  The idea is to pass the pointer to the exception instance up the call stack, but I am not sure how to do this with 64-bit pointers.  I'd prefer if we can somehow pass a pointer to the exception instance, but if this is impossible, I guess we'll have to resort to an error code.  After all, it is just a sample.

**Comment by f0rki** [comment]
FYI: I added a paragraph that clarifies this issue to the text.

**Comment by vgxbj** [comment]
Thanks a lot 😃
