### ISSUE TITLE
Status of extending to C++/C API

### ISSUE THREAD

**Issue by LumenUI** [f0rki/mapping-high-level-constructs-to-llvm-ir#35]
Will you ever extend this GitBook to the LLVM IRBuilder API? If not, I’ll see what I can do to add another category for that.

**Comment by archfrog** [comment]
Personally, I prefer the simplicity of the IR samples.  I don't have any plans to add anything related to the API, but I don't know about the others reading this.

**Comment by aiko-is-bored** [comment]
I as well like the IR examples, but many people (myself included) have gone to MHLCTLR to implement certain aspects into their language. I am hoping for a hashmap implementation, as holy fuck it is hard to write in LLVM IR (write it well that is).

**Comment by archfrog** [comment]
Ehm, what does `MHLCTLR` mean?  I tried to google it, but found nothing relevant :-)

**Comment by f0rki** [comment]
> Personally, I prefer the simplicity of the IR samples. I don't have any plans to add anything related to the API, [...]

I agree with this. I think the LLVM docs would be the better place for information on the actual API.

**Comment by aiko-is-bored** [comment]
> > Personally, I prefer the simplicity of the IR samples. I don't have any plans to add anything related to the API, [...]
> 
> I agree with this. I think the LLVM docs would be the better place for information on the actual API.

True.

**Comment by YurySolovyov** [comment]
> Ehm, what does `MHLCTLR` mean? I tried to google it, but found nothing relevant :-)

mapping-high-level-constructs-to-llvm-ir I guess, but last one does not match :)
