### ISSUE TITLE
invalid links on exception-handling resources

### ISSUE THREAD

**Issue by arbipher** [f0rki/mapping-high-level-constructs-to-llvm-ir#38]
https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/exception-handling/resources.html

https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/exception-handling/www.hexblog.com/wp-content/uploads/2012/06/Recon-2012-Skochinsky-Compiler-Internals.pdf

Readthedocs treats it as relative url which should be an absolute one.

**Comment by f0rki** [comment]
thanks! fixed now :)
