### ISSUE TITLE
gitbook doesn't highlight llvm ir syntax

### ISSUE THREAD

**Issue by f0rki** [f0rki/mapping-high-level-constructs-to-llvm-ir#9]
This makes it not so nice to read.

Maybe
-  using `ll` as language tag is wrong.
-  no [highlight.js](https://github.com/isagalaev/highlight.js) support

**Comment by archfrog** [comment]
Strange, when I open an LLVM IR file from the repository, it **is** highlighted properly.  I am using Chrome, which browser are you using?

Please see the attached screen capture.
![2016-10-26 10_05_22-mapping-high-level-constructs-to-llvm-ir_listing_0 ll at master f0rki_mapping-](https://cloud.githubusercontent.com/assets/1729893/19718064/f9c04d66-9b63-11e6-9fa7-59350ff67b6b.png)

**Comment by f0rki** [comment]
yes github does highlight it properly, but not gitbooks.io --> see e.g. https://f0rki.gitbooks.io/mapping-high-level-constructs-to-llvm-ir/content/mapping-basic-constructs-to-llvm-ir/global-variables.html

**Comment by archfrog** [comment]
Oh, bummer :-)  

Are you good at JavaScript?  I have no experience in it.  The only solution seems to be to add support for LLVM IR to highlight.js.  I've tried adding languages to other syntax highlighters and it usually takes like a single evening to do.  I can take a shot at it or do you prefer to do it?

**Comment by f0rki** [comment]
I wouldn't say that I'm good at JavaScript, but I think I can manage to do it. I guess I can use the one from github or pygments as a base.

**Comment by archfrog** [comment]
Okay, thanks :)

**Comment by f0rki** [comment]
Pull request for highlight.js at https://github.com/isagalaev/highlight.js/pull/1337

Now we have to wait until gitbook integrates this...

**Comment by f0rki** [comment]
Tried to switch to the gitbook pygments plugin with 4585e4d76c846feeb0c3477a1e8dabab3f1cbb01 . works fine locally, but no pygments on the gitbook build server...

**Comment by f0rki** [comment]
My pull request for highlight.js at isagalaev/highlight.js#1337 was finally merged. Now we just have to wait for a release or gitbook to integrate it.

**Comment by f0rki** [comment]
Turns out gitbook.com is super slow in incorporating new highlightjs versions... I openend a pull request: GitbookIO/plugin-highlight/pull/9

**Comment by f0rki** [comment]
I switched to readthedocs.

https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io
